SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT
        A.CAR_ID,
        A.CAR_TYPE,
        ROUND((30 * DAILY_FEE) * (1 - NVL(B.DISCOUNT_RATE, 0) / 100), 0) AS FEE
    FROM
        CAR_RENTAL_COMPANY_CAR A
    LEFT OUTER JOIN
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON
        A.CAR_TYPE = B.CAR_TYPE AND B.DURATION_TYPE = '30일 이상'
    WHERE
        A.CAR_TYPE IN ('세단', 'SUV')
        AND NOT EXISTS (
            SELECT C.CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
            WHERE
                A.CAR_ID = C.CAR_ID
                AND C.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
                AND C.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
        )
)
WHERE FEE >= 500000 AND FEE < 2000000 
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;