SELECT
    Sub.CAR_ID,
    TO_CHAR(Sub.NUMERIC_AVG_DURATION, 'FM999999.0') AS AVERAGE_DURATION
FROM (
    SELECT
        CAR_ID,
        ROUND(AVG(END_DATE - START_DATE + 1), 1) AS NUMERIC_AVG_DURATION
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY
        CAR_ID
    HAVING
        AVG(END_DATE - START_DATE + 1) >= 7 
) Sub
ORDER BY
    Sub.NUMERIC_AVG_DURATION DESC, 
    Sub.CAR_ID DESC;            